paginate: 5
paginate_path: "/blog/page/:num/"

permalink: pretty

safe: true
lsi: false
highlighter: rouge
markdown: kramdown

static_url: /static/
production_url : "http://siggame.io"

excerpt_seperator: <!--more-->

gems:
  - jekyll-paginate

